version: '3.8'

services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  credit-risk-pipeline:
    build: .
    volumes:
      - .:/app
    command: python src/data_processing.py
<<<<<<< HEAD
credit-risk-target:
  build: .
  volumes:
    - .:/app
  command: python src/target_engineering.py
=======
>>>>>>> 5e10476245091a457d2a9e29d1609e1221d0a8d8
